### ISSUE TITLE
eyed3 and/or libmagic dependency problem

### ISSUE THREAD

**Issue by vassiliskrikonis** [tyiannak/multimodalAnalysis#10]
I've tried running the `audio/example08.py` with no success.
With `eyed3==0.7.11` and `eyed3==0.8.0` it produces the following error:

```
Error: file not found or other I/O error. (DECODING FAILED)
Traceback (most recent call last):
  File "example08.py", line 16, in <module>
    duration = len(s) / float(fs)
TypeError: object of type 'int' has no len()
```

and with latest eyed3 the following error occurs

```
Traceback (most recent call last):
  File "example08.py", line 9, in <module>
    from pyAudioAnalysis import audioFeatureExtraction as aF
  File "/Users/vassiliskrikonis/Projects/pyAudioAnalysis/pyAudioAnalysis/audioFeatureExtraction.py", line 10, in <module>
    from pyAudioAnalysis import audioBasicIO
  File "/Users/vassiliskrikonis/Projects/pyAudioAnalysis/pyAudioAnalysis/audioBasicIO.py", line 2, in <module>
    import os, glob, eyed3, ntpath, shutil, numpy
  File "/anaconda3/lib/python3.6/site-packages/eyed3/__init__.py", line 32, in <module>
    from .utils.log import log                                          # noqa: E402
  File "/anaconda3/lib/python3.6/site-packages/eyed3/utils/__init__.py", line 66, in <module>
    _mime_types = MagicTypes()
  File "/anaconda3/lib/python3.6/site-packages/eyed3/utils/__init__.py", line 54, in __init__
    keep_going=False)
TypeError: __init__() got an unexpected keyword argument 'mime'
Exception ignored in: <bound method Magic.__del__ of <eyed3.utils.MagicTypes object at 0x116a22940>>
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/magic/__init__.py", line 19, in __del__
    ffi.close(self.cookie)
AttributeError: 'MagicTypes' object has no attribute 'cookie'
```

(I'm running MacOS 10.13 and install libmagic with brew)

**Comment by tyiannak** [comment]
Thanx, the error (Error: file not found or other I/O error. (DECODING FAILED)) was due to the fact that the input file was not added in the repo. That should be ok now in the 9_deep_learning branch (not merged to master yet)

**Comment by vassiliskrikonis** [comment]
Thanks! So the required versions are `eyed3==0.7.11` or `eyed3==0.8.0` and the example needs to be run from the `audio` folder.
